blank_issues_enabled: false
contact_links:
  - name: Troubleshooting Guide
    url: https://github.com/jxlarrea/Voice-Satellite-Card-for-Home-Assistant#troubleshooting
    about: Check the troubleshooting section before opening an issue